name: Links update

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fw-update script
        run: |
          python fw-update.py
          git config --global user.name '8Bit Gamer'
          git config --global user.email '8bitgamer2024@gmail.com'
          git add updates.json
          git commit -m 'CFW/SFW Update' || echo "No changes to commit"
          git push

      - name: Run shop-update script
        run: |
          python shop-update.py
          git config --global user.name '8Bit Gamer'
          git config --global user.email '8bitgamer2024@gmail.com'
          git add tinfoil.json
          git commit -m 'Shop Update' || echo "No changes to commit"
          git push
