name: RC

on:
  workflow_dispatch:

jobs:
  Building:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v4
      with:
        repository: laleeroy/8bit-updater
        ref: stable
        path: 8bit-updater
        submodules: recursive
        token: ${{ secrets.GH_TOKEN }}

    - name: Install Dependencies
      run: |
        sudo apt update -y
        sudo apt install build-essential -y

    - name: Compiling
      run: |
        make -C 8bit-updater -j$(nproc)

    - uses: actions/upload-artifact@v4
      with:
        name: 8bit-updater
        path: 8bit-updater/8bit-updater.nro
